import type { NextPage } from "next";
import Head from "next/head";
import Player from "../components/Player";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>dr34m radio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          {"audio::-webkit-media-controls-timeline { display:none; }"}
        </style>
      </Head>

      <main>
        <h1>dr34m-radio</h1>

        <Player
          autoPlay={false}
          controls={true}
          src="https://ssl.srvstm.com:19480/;%22%3E"
        />
      </main>
    </div>
  );
};

export default Home;
