import { Box, Flex, Text } from "@chakra-ui/layout";
import type { NextPage } from "next";
import Head from "next/head";
import Player from "../components/player";

const Home: NextPage = () => {
  return (
    <Box as="main" w="100%" h="100%" minH="100vh" color="#111">
      <Head>
        <title>dr34m radio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          {"audio::-webkit-media-controls-timeline { display:none; }"}
        </style>
      </Head>
      <Text as="h1" fontWeight="bold" fontSize="6xl" textAlign="center" p={8}>
        dr34m radio
      </Text>

      <Player
        autoPlay={false}
        controls={true}
        src="https://ssl.srvstm.com:19480/;%22%3E"
      />
    </Box>
  );
};

export default Home;
